version: '3'
services:
 nginx:
  image: nginx
  container_name: helloapp
  build: 
   context: frontend
  ports:
   - "3000:80"
   - "443:443"
  volumes:
   - "$PWD/frontend/index.html:/usr/share/nginx/html/index.html"
   - "$PWD/frontend/nginx.conf:/etc/nginx/nginx.conf"
   - "$PWD/frontend/ssl:/etc/nginx/ssl/"
  networks:
   - client

#  jenkins:
#   container_name: jenkins2
#   image: jenkins/jenkins
#   ports: 
#    - "8080:8080"
#    - "50000:50000"
#   volumes:
#    - "$PWD/jenkinsdemo/jenkins_home:/var/jenkins_home"
#   networks:
#    - client
 
# node:
#  image: "node:8"
#  build:
#   context: ./backend
#  working_dir: /home/app
#  command: "npm run dev"
#  networks:
#   - client 

networks:
 client:
