version: '3'
services:
 nginx:
  image: nginx
  container_name: helloapp
  build: 
   context: frontend
  ports:
   - "3001:80"
  volumes:
   - "$PWD/frontend:/usr/share/nginx/html"
  networks:
   - client

 jenkins:
  container_name: jenkins2
  image: jenkins/jenkins
  ports: 
   - "8080:8080"
  volumes:
   - "$PWD/jenkinsdemo/jenkins_home:/var/jenkins_home"
  networks:
   - client
 
 node:
  image: "node:8"
  build:
   context: ./backend
  working_dir: /home/app
  command: "npm run dev"
  

networks:
 client:
